/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProcessTextForm type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProcessTextForm{}

// ProcessTextForm struct for ProcessTextForm
type ProcessTextForm struct {
	Name string `json:"name"`
	Content string `json:"content"`
	CollectionName NullableString `json:"collection_name,omitempty"`
}

type _ProcessTextForm ProcessTextForm

// NewProcessTextForm instantiates a new ProcessTextForm object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProcessTextForm(name string, content string) *ProcessTextForm {
	this := ProcessTextForm{}
	this.Name = name
	this.Content = content
	return &this
}

// NewProcessTextFormWithDefaults instantiates a new ProcessTextForm object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProcessTextFormWithDefaults() *ProcessTextForm {
	this := ProcessTextForm{}
	return &this
}

// GetName returns the Name field value
func (o *ProcessTextForm) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ProcessTextForm) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ProcessTextForm) SetName(v string) {
	o.Name = v
}

// GetContent returns the Content field value
func (o *ProcessTextForm) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *ProcessTextForm) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *ProcessTextForm) SetContent(v string) {
	o.Content = v
}

// GetCollectionName returns the CollectionName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProcessTextForm) GetCollectionName() string {
	if o == nil || IsNil(o.CollectionName.Get()) {
		var ret string
		return ret
	}
	return *o.CollectionName.Get()
}

// GetCollectionNameOk returns a tuple with the CollectionName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProcessTextForm) GetCollectionNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CollectionName.Get(), o.CollectionName.IsSet()
}

// HasCollectionName returns a boolean if a field has been set.
func (o *ProcessTextForm) HasCollectionName() bool {
	if o != nil && o.CollectionName.IsSet() {
		return true
	}

	return false
}

// SetCollectionName gets a reference to the given NullableString and assigns it to the CollectionName field.
func (o *ProcessTextForm) SetCollectionName(v string) {
	o.CollectionName.Set(&v)
}
// SetCollectionNameNil sets the value for CollectionName to be an explicit nil
func (o *ProcessTextForm) SetCollectionNameNil() {
	o.CollectionName.Set(nil)
}

// UnsetCollectionName ensures that no value is present for CollectionName, not even an explicit nil
func (o *ProcessTextForm) UnsetCollectionName() {
	o.CollectionName.Unset()
}

func (o ProcessTextForm) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProcessTextForm) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["content"] = o.Content
	if o.CollectionName.IsSet() {
		toSerialize["collection_name"] = o.CollectionName.Get()
	}
	return toSerialize, nil
}

func (o *ProcessTextForm) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"content",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProcessTextForm := _ProcessTextForm{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProcessTextForm)

	if err != nil {
		return err
	}

	*o = ProcessTextForm(varProcessTextForm)

	return err
}

type NullableProcessTextForm struct {
	value *ProcessTextForm
	isSet bool
}

func (v NullableProcessTextForm) Get() *ProcessTextForm {
	return v.value
}

func (v *NullableProcessTextForm) Set(val *ProcessTextForm) {
	v.value = val
	v.isSet = true
}

func (v NullableProcessTextForm) IsSet() bool {
	return v.isSet
}

func (v *NullableProcessTextForm) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProcessTextForm(val *ProcessTextForm) *NullableProcessTextForm {
	return &NullableProcessTextForm{value: val, isSet: true}
}

func (v NullableProcessTextForm) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProcessTextForm) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


