/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DirectConnectionsConfigForm type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DirectConnectionsConfigForm{}

// DirectConnectionsConfigForm struct for DirectConnectionsConfigForm
type DirectConnectionsConfigForm struct {
	ENABLE_DIRECT_CONNECTIONS bool `json:"ENABLE_DIRECT_CONNECTIONS"`
}

type _DirectConnectionsConfigForm DirectConnectionsConfigForm

// NewDirectConnectionsConfigForm instantiates a new DirectConnectionsConfigForm object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDirectConnectionsConfigForm(eNABLEDIRECTCONNECTIONS bool) *DirectConnectionsConfigForm {
	this := DirectConnectionsConfigForm{}
	this.ENABLE_DIRECT_CONNECTIONS = eNABLEDIRECTCONNECTIONS
	return &this
}

// NewDirectConnectionsConfigFormWithDefaults instantiates a new DirectConnectionsConfigForm object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDirectConnectionsConfigFormWithDefaults() *DirectConnectionsConfigForm {
	this := DirectConnectionsConfigForm{}
	return &this
}

// GetENABLE_DIRECT_CONNECTIONS returns the ENABLE_DIRECT_CONNECTIONS field value
func (o *DirectConnectionsConfigForm) GetENABLE_DIRECT_CONNECTIONS() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ENABLE_DIRECT_CONNECTIONS
}

// GetENABLE_DIRECT_CONNECTIONSOk returns a tuple with the ENABLE_DIRECT_CONNECTIONS field value
// and a boolean to check if the value has been set.
func (o *DirectConnectionsConfigForm) GetENABLE_DIRECT_CONNECTIONSOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ENABLE_DIRECT_CONNECTIONS, true
}

// SetENABLE_DIRECT_CONNECTIONS sets field value
func (o *DirectConnectionsConfigForm) SetENABLE_DIRECT_CONNECTIONS(v bool) {
	o.ENABLE_DIRECT_CONNECTIONS = v
}

func (o DirectConnectionsConfigForm) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DirectConnectionsConfigForm) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ENABLE_DIRECT_CONNECTIONS"] = o.ENABLE_DIRECT_CONNECTIONS
	return toSerialize, nil
}

func (o *DirectConnectionsConfigForm) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ENABLE_DIRECT_CONNECTIONS",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDirectConnectionsConfigForm := _DirectConnectionsConfigForm{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDirectConnectionsConfigForm)

	if err != nil {
		return err
	}

	*o = DirectConnectionsConfigForm(varDirectConnectionsConfigForm)

	return err
}

type NullableDirectConnectionsConfigForm struct {
	value *DirectConnectionsConfigForm
	isSet bool
}

func (v NullableDirectConnectionsConfigForm) Get() *DirectConnectionsConfigForm {
	return v.value
}

func (v *NullableDirectConnectionsConfigForm) Set(val *DirectConnectionsConfigForm) {
	v.value = val
	v.isSet = true
}

func (v NullableDirectConnectionsConfigForm) IsSet() bool {
	return v.isSet
}

func (v *NullableDirectConnectionsConfigForm) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDirectConnectionsConfigForm(val *DirectConnectionsConfigForm) *NullableDirectConnectionsConfigForm {
	return &NullableDirectConnectionsConfigForm{value: val, isSet: true}
}

func (v NullableDirectConnectionsConfigForm) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDirectConnectionsConfigForm) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


