/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeletePipelineForm type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeletePipelineForm{}

// DeletePipelineForm struct for DeletePipelineForm
type DeletePipelineForm struct {
	Id string `json:"id"`
	UrlIdx int32 `json:"urlIdx"`
}

type _DeletePipelineForm DeletePipelineForm

// NewDeletePipelineForm instantiates a new DeletePipelineForm object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeletePipelineForm(id string, urlIdx int32) *DeletePipelineForm {
	this := DeletePipelineForm{}
	this.Id = id
	this.UrlIdx = urlIdx
	return &this
}

// NewDeletePipelineFormWithDefaults instantiates a new DeletePipelineForm object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeletePipelineFormWithDefaults() *DeletePipelineForm {
	this := DeletePipelineForm{}
	return &this
}

// GetId returns the Id field value
func (o *DeletePipelineForm) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DeletePipelineForm) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DeletePipelineForm) SetId(v string) {
	o.Id = v
}

// GetUrlIdx returns the UrlIdx field value
func (o *DeletePipelineForm) GetUrlIdx() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.UrlIdx
}

// GetUrlIdxOk returns a tuple with the UrlIdx field value
// and a boolean to check if the value has been set.
func (o *DeletePipelineForm) GetUrlIdxOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UrlIdx, true
}

// SetUrlIdx sets field value
func (o *DeletePipelineForm) SetUrlIdx(v int32) {
	o.UrlIdx = v
}

func (o DeletePipelineForm) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeletePipelineForm) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["urlIdx"] = o.UrlIdx
	return toSerialize, nil
}

func (o *DeletePipelineForm) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"urlIdx",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeletePipelineForm := _DeletePipelineForm{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeletePipelineForm)

	if err != nil {
		return err
	}

	*o = DeletePipelineForm(varDeletePipelineForm)

	return err
}

type NullableDeletePipelineForm struct {
	value *DeletePipelineForm
	isSet bool
}

func (v NullableDeletePipelineForm) Get() *DeletePipelineForm {
	return v.value
}

func (v *NullableDeletePipelineForm) Set(val *DeletePipelineForm) {
	v.value = val
	v.isSet = true
}

func (v NullableDeletePipelineForm) IsSet() bool {
	return v.isSet
}

func (v *NullableDeletePipelineForm) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeletePipelineForm(val *DeletePipelineForm) *NullableDeletePipelineForm {
	return &NullableDeletePipelineForm{value: val, isSet: true}
}

func (v NullableDeletePipelineForm) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeletePipelineForm) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


