/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ModelNameForm type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelNameForm{}

// ModelNameForm struct for ModelNameForm
type ModelNameForm struct {
	Name string `json:"name"`
}

type _ModelNameForm ModelNameForm

// NewModelNameForm instantiates a new ModelNameForm object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelNameForm(name string) *ModelNameForm {
	this := ModelNameForm{}
	this.Name = name
	return &this
}

// NewModelNameFormWithDefaults instantiates a new ModelNameForm object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelNameFormWithDefaults() *ModelNameForm {
	this := ModelNameForm{}
	return &this
}

// GetName returns the Name field value
func (o *ModelNameForm) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ModelNameForm) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ModelNameForm) SetName(v string) {
	o.Name = v
}

func (o ModelNameForm) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelNameForm) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *ModelNameForm) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varModelNameForm := _ModelNameForm{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varModelNameForm)

	if err != nil {
		return err
	}

	*o = ModelNameForm(varModelNameForm)

	return err
}

type NullableModelNameForm struct {
	value *ModelNameForm
	isSet bool
}

func (v NullableModelNameForm) Get() *ModelNameForm {
	return v.value
}

func (v *NullableModelNameForm) Set(val *ModelNameForm) {
	v.value = val
	v.isSet = true
}

func (v NullableModelNameForm) IsSet() bool {
	return v.isSet
}

func (v *NullableModelNameForm) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelNameForm(val *ModelNameForm) *NullableModelNameForm {
	return &NullableModelNameForm{value: val, isSet: true}
}

func (v NullableModelNameForm) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelNameForm) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


