/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProcessFileForm type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProcessFileForm{}

// ProcessFileForm struct for ProcessFileForm
type ProcessFileForm struct {
	FileId string `json:"file_id"`
	Content NullableString `json:"content,omitempty"`
	CollectionName NullableString `json:"collection_name,omitempty"`
}

type _ProcessFileForm ProcessFileForm

// NewProcessFileForm instantiates a new ProcessFileForm object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProcessFileForm(fileId string) *ProcessFileForm {
	this := ProcessFileForm{}
	this.FileId = fileId
	return &this
}

// NewProcessFileFormWithDefaults instantiates a new ProcessFileForm object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProcessFileFormWithDefaults() *ProcessFileForm {
	this := ProcessFileForm{}
	return &this
}

// GetFileId returns the FileId field value
func (o *ProcessFileForm) GetFileId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FileId
}

// GetFileIdOk returns a tuple with the FileId field value
// and a boolean to check if the value has been set.
func (o *ProcessFileForm) GetFileIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FileId, true
}

// SetFileId sets field value
func (o *ProcessFileForm) SetFileId(v string) {
	o.FileId = v
}

// GetContent returns the Content field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProcessFileForm) GetContent() string {
	if o == nil || IsNil(o.Content.Get()) {
		var ret string
		return ret
	}
	return *o.Content.Get()
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProcessFileForm) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Content.Get(), o.Content.IsSet()
}

// HasContent returns a boolean if a field has been set.
func (o *ProcessFileForm) HasContent() bool {
	if o != nil && o.Content.IsSet() {
		return true
	}

	return false
}

// SetContent gets a reference to the given NullableString and assigns it to the Content field.
func (o *ProcessFileForm) SetContent(v string) {
	o.Content.Set(&v)
}
// SetContentNil sets the value for Content to be an explicit nil
func (o *ProcessFileForm) SetContentNil() {
	o.Content.Set(nil)
}

// UnsetContent ensures that no value is present for Content, not even an explicit nil
func (o *ProcessFileForm) UnsetContent() {
	o.Content.Unset()
}

// GetCollectionName returns the CollectionName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProcessFileForm) GetCollectionName() string {
	if o == nil || IsNil(o.CollectionName.Get()) {
		var ret string
		return ret
	}
	return *o.CollectionName.Get()
}

// GetCollectionNameOk returns a tuple with the CollectionName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProcessFileForm) GetCollectionNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CollectionName.Get(), o.CollectionName.IsSet()
}

// HasCollectionName returns a boolean if a field has been set.
func (o *ProcessFileForm) HasCollectionName() bool {
	if o != nil && o.CollectionName.IsSet() {
		return true
	}

	return false
}

// SetCollectionName gets a reference to the given NullableString and assigns it to the CollectionName field.
func (o *ProcessFileForm) SetCollectionName(v string) {
	o.CollectionName.Set(&v)
}
// SetCollectionNameNil sets the value for CollectionName to be an explicit nil
func (o *ProcessFileForm) SetCollectionNameNil() {
	o.CollectionName.Set(nil)
}

// UnsetCollectionName ensures that no value is present for CollectionName, not even an explicit nil
func (o *ProcessFileForm) UnsetCollectionName() {
	o.CollectionName.Unset()
}

func (o ProcessFileForm) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProcessFileForm) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["file_id"] = o.FileId
	if o.Content.IsSet() {
		toSerialize["content"] = o.Content.Get()
	}
	if o.CollectionName.IsSet() {
		toSerialize["collection_name"] = o.CollectionName.Get()
	}
	return toSerialize, nil
}

func (o *ProcessFileForm) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"file_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProcessFileForm := _ProcessFileForm{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProcessFileForm)

	if err != nil {
		return err
	}

	*o = ProcessFileForm(varProcessFileForm)

	return err
}

type NullableProcessFileForm struct {
	value *ProcessFileForm
	isSet bool
}

func (v NullableProcessFileForm) Get() *ProcessFileForm {
	return v.value
}

func (v *NullableProcessFileForm) Set(val *ProcessFileForm) {
	v.value = val
	v.isSet = true
}

func (v NullableProcessFileForm) IsSet() bool {
	return v.isSet
}

func (v *NullableProcessFileForm) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProcessFileForm(val *ProcessFileForm) *NullableProcessFileForm {
	return &NullableProcessFileForm{value: val, isSet: true}
}

func (v NullableProcessFileForm) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProcessFileForm) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


