/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ContentExtractionConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContentExtractionConfig{}

// ContentExtractionConfig struct for ContentExtractionConfig
type ContentExtractionConfig struct {
	Engine *string `json:"engine,omitempty"`
	TikaServerUrl NullableString `json:"tika_server_url,omitempty"`
	DocumentIntelligenceConfig NullableDocumentIntelligenceConfigForm `json:"document_intelligence_config,omitempty"`
}

// NewContentExtractionConfig instantiates a new ContentExtractionConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContentExtractionConfig() *ContentExtractionConfig {
	this := ContentExtractionConfig{}
	var engine string = ""
	this.Engine = &engine
	return &this
}

// NewContentExtractionConfigWithDefaults instantiates a new ContentExtractionConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContentExtractionConfigWithDefaults() *ContentExtractionConfig {
	this := ContentExtractionConfig{}
	var engine string = ""
	this.Engine = &engine
	return &this
}

// GetEngine returns the Engine field value if set, zero value otherwise.
func (o *ContentExtractionConfig) GetEngine() string {
	if o == nil || IsNil(o.Engine) {
		var ret string
		return ret
	}
	return *o.Engine
}

// GetEngineOk returns a tuple with the Engine field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentExtractionConfig) GetEngineOk() (*string, bool) {
	if o == nil || IsNil(o.Engine) {
		return nil, false
	}
	return o.Engine, true
}

// HasEngine returns a boolean if a field has been set.
func (o *ContentExtractionConfig) HasEngine() bool {
	if o != nil && !IsNil(o.Engine) {
		return true
	}

	return false
}

// SetEngine gets a reference to the given string and assigns it to the Engine field.
func (o *ContentExtractionConfig) SetEngine(v string) {
	o.Engine = &v
}

// GetTikaServerUrl returns the TikaServerUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ContentExtractionConfig) GetTikaServerUrl() string {
	if o == nil || IsNil(o.TikaServerUrl.Get()) {
		var ret string
		return ret
	}
	return *o.TikaServerUrl.Get()
}

// GetTikaServerUrlOk returns a tuple with the TikaServerUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ContentExtractionConfig) GetTikaServerUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TikaServerUrl.Get(), o.TikaServerUrl.IsSet()
}

// HasTikaServerUrl returns a boolean if a field has been set.
func (o *ContentExtractionConfig) HasTikaServerUrl() bool {
	if o != nil && o.TikaServerUrl.IsSet() {
		return true
	}

	return false
}

// SetTikaServerUrl gets a reference to the given NullableString and assigns it to the TikaServerUrl field.
func (o *ContentExtractionConfig) SetTikaServerUrl(v string) {
	o.TikaServerUrl.Set(&v)
}
// SetTikaServerUrlNil sets the value for TikaServerUrl to be an explicit nil
func (o *ContentExtractionConfig) SetTikaServerUrlNil() {
	o.TikaServerUrl.Set(nil)
}

// UnsetTikaServerUrl ensures that no value is present for TikaServerUrl, not even an explicit nil
func (o *ContentExtractionConfig) UnsetTikaServerUrl() {
	o.TikaServerUrl.Unset()
}

// GetDocumentIntelligenceConfig returns the DocumentIntelligenceConfig field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ContentExtractionConfig) GetDocumentIntelligenceConfig() DocumentIntelligenceConfigForm {
	if o == nil || IsNil(o.DocumentIntelligenceConfig.Get()) {
		var ret DocumentIntelligenceConfigForm
		return ret
	}
	return *o.DocumentIntelligenceConfig.Get()
}

// GetDocumentIntelligenceConfigOk returns a tuple with the DocumentIntelligenceConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ContentExtractionConfig) GetDocumentIntelligenceConfigOk() (*DocumentIntelligenceConfigForm, bool) {
	if o == nil {
		return nil, false
	}
	return o.DocumentIntelligenceConfig.Get(), o.DocumentIntelligenceConfig.IsSet()
}

// HasDocumentIntelligenceConfig returns a boolean if a field has been set.
func (o *ContentExtractionConfig) HasDocumentIntelligenceConfig() bool {
	if o != nil && o.DocumentIntelligenceConfig.IsSet() {
		return true
	}

	return false
}

// SetDocumentIntelligenceConfig gets a reference to the given NullableDocumentIntelligenceConfigForm and assigns it to the DocumentIntelligenceConfig field.
func (o *ContentExtractionConfig) SetDocumentIntelligenceConfig(v DocumentIntelligenceConfigForm) {
	o.DocumentIntelligenceConfig.Set(&v)
}
// SetDocumentIntelligenceConfigNil sets the value for DocumentIntelligenceConfig to be an explicit nil
func (o *ContentExtractionConfig) SetDocumentIntelligenceConfigNil() {
	o.DocumentIntelligenceConfig.Set(nil)
}

// UnsetDocumentIntelligenceConfig ensures that no value is present for DocumentIntelligenceConfig, not even an explicit nil
func (o *ContentExtractionConfig) UnsetDocumentIntelligenceConfig() {
	o.DocumentIntelligenceConfig.Unset()
}

func (o ContentExtractionConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContentExtractionConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Engine) {
		toSerialize["engine"] = o.Engine
	}
	if o.TikaServerUrl.IsSet() {
		toSerialize["tika_server_url"] = o.TikaServerUrl.Get()
	}
	if o.DocumentIntelligenceConfig.IsSet() {
		toSerialize["document_intelligence_config"] = o.DocumentIntelligenceConfig.Get()
	}
	return toSerialize, nil
}

type NullableContentExtractionConfig struct {
	value *ContentExtractionConfig
	isSet bool
}

func (v NullableContentExtractionConfig) Get() *ContentExtractionConfig {
	return v.value
}

func (v *NullableContentExtractionConfig) Set(val *ContentExtractionConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableContentExtractionConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableContentExtractionConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContentExtractionConfig(val *ContentExtractionConfig) *NullableContentExtractionConfig {
	return &NullableContentExtractionConfig{value: val, isSet: true}
}

func (v NullableContentExtractionConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContentExtractionConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


