/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TaskConfigForm type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TaskConfigForm{}

// TaskConfigForm struct for TaskConfigForm
type TaskConfigForm struct {
	TASK_MODEL NullableString `json:"TASK_MODEL"`
	TASK_MODEL_EXTERNAL NullableString `json:"TASK_MODEL_EXTERNAL"`
	ENABLE_TITLE_GENERATION bool `json:"ENABLE_TITLE_GENERATION"`
	TITLE_GENERATION_PROMPT_TEMPLATE string `json:"TITLE_GENERATION_PROMPT_TEMPLATE"`
	IMAGE_PROMPT_GENERATION_PROMPT_TEMPLATE string `json:"IMAGE_PROMPT_GENERATION_PROMPT_TEMPLATE"`
	ENABLE_AUTOCOMPLETE_GENERATION bool `json:"ENABLE_AUTOCOMPLETE_GENERATION"`
	AUTOCOMPLETE_GENERATION_INPUT_MAX_LENGTH int32 `json:"AUTOCOMPLETE_GENERATION_INPUT_MAX_LENGTH"`
	TAGS_GENERATION_PROMPT_TEMPLATE string `json:"TAGS_GENERATION_PROMPT_TEMPLATE"`
	ENABLE_TAGS_GENERATION bool `json:"ENABLE_TAGS_GENERATION"`
	ENABLE_SEARCH_QUERY_GENERATION bool `json:"ENABLE_SEARCH_QUERY_GENERATION"`
	ENABLE_RETRIEVAL_QUERY_GENERATION bool `json:"ENABLE_RETRIEVAL_QUERY_GENERATION"`
	QUERY_GENERATION_PROMPT_TEMPLATE string `json:"QUERY_GENERATION_PROMPT_TEMPLATE"`
	TOOLS_FUNCTION_CALLING_PROMPT_TEMPLATE string `json:"TOOLS_FUNCTION_CALLING_PROMPT_TEMPLATE"`
}

type _TaskConfigForm TaskConfigForm

// NewTaskConfigForm instantiates a new TaskConfigForm object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTaskConfigForm(tASKMODEL NullableString, tASKMODELEXTERNAL NullableString, eNABLETITLEGENERATION bool, tITLEGENERATIONPROMPTTEMPLATE string, iMAGEPROMPTGENERATIONPROMPTTEMPLATE string, eNABLEAUTOCOMPLETEGENERATION bool, aUTOCOMPLETEGENERATIONINPUTMAXLENGTH int32, tAGSGENERATIONPROMPTTEMPLATE string, eNABLETAGSGENERATION bool, eNABLESEARCHQUERYGENERATION bool, eNABLERETRIEVALQUERYGENERATION bool, qUERYGENERATIONPROMPTTEMPLATE string, tOOLSFUNCTIONCALLINGPROMPTTEMPLATE string) *TaskConfigForm {
	this := TaskConfigForm{}
	this.TASK_MODEL = tASKMODEL
	this.TASK_MODEL_EXTERNAL = tASKMODELEXTERNAL
	this.ENABLE_TITLE_GENERATION = eNABLETITLEGENERATION
	this.TITLE_GENERATION_PROMPT_TEMPLATE = tITLEGENERATIONPROMPTTEMPLATE
	this.IMAGE_PROMPT_GENERATION_PROMPT_TEMPLATE = iMAGEPROMPTGENERATIONPROMPTTEMPLATE
	this.ENABLE_AUTOCOMPLETE_GENERATION = eNABLEAUTOCOMPLETEGENERATION
	this.AUTOCOMPLETE_GENERATION_INPUT_MAX_LENGTH = aUTOCOMPLETEGENERATIONINPUTMAXLENGTH
	this.TAGS_GENERATION_PROMPT_TEMPLATE = tAGSGENERATIONPROMPTTEMPLATE
	this.ENABLE_TAGS_GENERATION = eNABLETAGSGENERATION
	this.ENABLE_SEARCH_QUERY_GENERATION = eNABLESEARCHQUERYGENERATION
	this.ENABLE_RETRIEVAL_QUERY_GENERATION = eNABLERETRIEVALQUERYGENERATION
	this.QUERY_GENERATION_PROMPT_TEMPLATE = qUERYGENERATIONPROMPTTEMPLATE
	this.TOOLS_FUNCTION_CALLING_PROMPT_TEMPLATE = tOOLSFUNCTIONCALLINGPROMPTTEMPLATE
	return &this
}

// NewTaskConfigFormWithDefaults instantiates a new TaskConfigForm object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTaskConfigFormWithDefaults() *TaskConfigForm {
	this := TaskConfigForm{}
	return &this
}

// GetTASK_MODEL returns the TASK_MODEL field value
// If the value is explicit nil, the zero value for string will be returned
func (o *TaskConfigForm) GetTASK_MODEL() string {
	if o == nil || o.TASK_MODEL.Get() == nil {
		var ret string
		return ret
	}

	return *o.TASK_MODEL.Get()
}

// GetTASK_MODELOk returns a tuple with the TASK_MODEL field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TaskConfigForm) GetTASK_MODELOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TASK_MODEL.Get(), o.TASK_MODEL.IsSet()
}

// SetTASK_MODEL sets field value
func (o *TaskConfigForm) SetTASK_MODEL(v string) {
	o.TASK_MODEL.Set(&v)
}

// GetTASK_MODEL_EXTERNAL returns the TASK_MODEL_EXTERNAL field value
// If the value is explicit nil, the zero value for string will be returned
func (o *TaskConfigForm) GetTASK_MODEL_EXTERNAL() string {
	if o == nil || o.TASK_MODEL_EXTERNAL.Get() == nil {
		var ret string
		return ret
	}

	return *o.TASK_MODEL_EXTERNAL.Get()
}

// GetTASK_MODEL_EXTERNALOk returns a tuple with the TASK_MODEL_EXTERNAL field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TaskConfigForm) GetTASK_MODEL_EXTERNALOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TASK_MODEL_EXTERNAL.Get(), o.TASK_MODEL_EXTERNAL.IsSet()
}

// SetTASK_MODEL_EXTERNAL sets field value
func (o *TaskConfigForm) SetTASK_MODEL_EXTERNAL(v string) {
	o.TASK_MODEL_EXTERNAL.Set(&v)
}

// GetENABLE_TITLE_GENERATION returns the ENABLE_TITLE_GENERATION field value
func (o *TaskConfigForm) GetENABLE_TITLE_GENERATION() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ENABLE_TITLE_GENERATION
}

// GetENABLE_TITLE_GENERATIONOk returns a tuple with the ENABLE_TITLE_GENERATION field value
// and a boolean to check if the value has been set.
func (o *TaskConfigForm) GetENABLE_TITLE_GENERATIONOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ENABLE_TITLE_GENERATION, true
}

// SetENABLE_TITLE_GENERATION sets field value
func (o *TaskConfigForm) SetENABLE_TITLE_GENERATION(v bool) {
	o.ENABLE_TITLE_GENERATION = v
}

// GetTITLE_GENERATION_PROMPT_TEMPLATE returns the TITLE_GENERATION_PROMPT_TEMPLATE field value
func (o *TaskConfigForm) GetTITLE_GENERATION_PROMPT_TEMPLATE() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TITLE_GENERATION_PROMPT_TEMPLATE
}

// GetTITLE_GENERATION_PROMPT_TEMPLATEOk returns a tuple with the TITLE_GENERATION_PROMPT_TEMPLATE field value
// and a boolean to check if the value has been set.
func (o *TaskConfigForm) GetTITLE_GENERATION_PROMPT_TEMPLATEOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TITLE_GENERATION_PROMPT_TEMPLATE, true
}

// SetTITLE_GENERATION_PROMPT_TEMPLATE sets field value
func (o *TaskConfigForm) SetTITLE_GENERATION_PROMPT_TEMPLATE(v string) {
	o.TITLE_GENERATION_PROMPT_TEMPLATE = v
}

// GetIMAGE_PROMPT_GENERATION_PROMPT_TEMPLATE returns the IMAGE_PROMPT_GENERATION_PROMPT_TEMPLATE field value
func (o *TaskConfigForm) GetIMAGE_PROMPT_GENERATION_PROMPT_TEMPLATE() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IMAGE_PROMPT_GENERATION_PROMPT_TEMPLATE
}

// GetIMAGE_PROMPT_GENERATION_PROMPT_TEMPLATEOk returns a tuple with the IMAGE_PROMPT_GENERATION_PROMPT_TEMPLATE field value
// and a boolean to check if the value has been set.
func (o *TaskConfigForm) GetIMAGE_PROMPT_GENERATION_PROMPT_TEMPLATEOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IMAGE_PROMPT_GENERATION_PROMPT_TEMPLATE, true
}

// SetIMAGE_PROMPT_GENERATION_PROMPT_TEMPLATE sets field value
func (o *TaskConfigForm) SetIMAGE_PROMPT_GENERATION_PROMPT_TEMPLATE(v string) {
	o.IMAGE_PROMPT_GENERATION_PROMPT_TEMPLATE = v
}

// GetENABLE_AUTOCOMPLETE_GENERATION returns the ENABLE_AUTOCOMPLETE_GENERATION field value
func (o *TaskConfigForm) GetENABLE_AUTOCOMPLETE_GENERATION() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ENABLE_AUTOCOMPLETE_GENERATION
}

// GetENABLE_AUTOCOMPLETE_GENERATIONOk returns a tuple with the ENABLE_AUTOCOMPLETE_GENERATION field value
// and a boolean to check if the value has been set.
func (o *TaskConfigForm) GetENABLE_AUTOCOMPLETE_GENERATIONOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ENABLE_AUTOCOMPLETE_GENERATION, true
}

// SetENABLE_AUTOCOMPLETE_GENERATION sets field value
func (o *TaskConfigForm) SetENABLE_AUTOCOMPLETE_GENERATION(v bool) {
	o.ENABLE_AUTOCOMPLETE_GENERATION = v
}

// GetAUTOCOMPLETE_GENERATION_INPUT_MAX_LENGTH returns the AUTOCOMPLETE_GENERATION_INPUT_MAX_LENGTH field value
func (o *TaskConfigForm) GetAUTOCOMPLETE_GENERATION_INPUT_MAX_LENGTH() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AUTOCOMPLETE_GENERATION_INPUT_MAX_LENGTH
}

// GetAUTOCOMPLETE_GENERATION_INPUT_MAX_LENGTHOk returns a tuple with the AUTOCOMPLETE_GENERATION_INPUT_MAX_LENGTH field value
// and a boolean to check if the value has been set.
func (o *TaskConfigForm) GetAUTOCOMPLETE_GENERATION_INPUT_MAX_LENGTHOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AUTOCOMPLETE_GENERATION_INPUT_MAX_LENGTH, true
}

// SetAUTOCOMPLETE_GENERATION_INPUT_MAX_LENGTH sets field value
func (o *TaskConfigForm) SetAUTOCOMPLETE_GENERATION_INPUT_MAX_LENGTH(v int32) {
	o.AUTOCOMPLETE_GENERATION_INPUT_MAX_LENGTH = v
}

// GetTAGS_GENERATION_PROMPT_TEMPLATE returns the TAGS_GENERATION_PROMPT_TEMPLATE field value
func (o *TaskConfigForm) GetTAGS_GENERATION_PROMPT_TEMPLATE() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TAGS_GENERATION_PROMPT_TEMPLATE
}

// GetTAGS_GENERATION_PROMPT_TEMPLATEOk returns a tuple with the TAGS_GENERATION_PROMPT_TEMPLATE field value
// and a boolean to check if the value has been set.
func (o *TaskConfigForm) GetTAGS_GENERATION_PROMPT_TEMPLATEOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TAGS_GENERATION_PROMPT_TEMPLATE, true
}

// SetTAGS_GENERATION_PROMPT_TEMPLATE sets field value
func (o *TaskConfigForm) SetTAGS_GENERATION_PROMPT_TEMPLATE(v string) {
	o.TAGS_GENERATION_PROMPT_TEMPLATE = v
}

// GetENABLE_TAGS_GENERATION returns the ENABLE_TAGS_GENERATION field value
func (o *TaskConfigForm) GetENABLE_TAGS_GENERATION() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ENABLE_TAGS_GENERATION
}

// GetENABLE_TAGS_GENERATIONOk returns a tuple with the ENABLE_TAGS_GENERATION field value
// and a boolean to check if the value has been set.
func (o *TaskConfigForm) GetENABLE_TAGS_GENERATIONOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ENABLE_TAGS_GENERATION, true
}

// SetENABLE_TAGS_GENERATION sets field value
func (o *TaskConfigForm) SetENABLE_TAGS_GENERATION(v bool) {
	o.ENABLE_TAGS_GENERATION = v
}

// GetENABLE_SEARCH_QUERY_GENERATION returns the ENABLE_SEARCH_QUERY_GENERATION field value
func (o *TaskConfigForm) GetENABLE_SEARCH_QUERY_GENERATION() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ENABLE_SEARCH_QUERY_GENERATION
}

// GetENABLE_SEARCH_QUERY_GENERATIONOk returns a tuple with the ENABLE_SEARCH_QUERY_GENERATION field value
// and a boolean to check if the value has been set.
func (o *TaskConfigForm) GetENABLE_SEARCH_QUERY_GENERATIONOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ENABLE_SEARCH_QUERY_GENERATION, true
}

// SetENABLE_SEARCH_QUERY_GENERATION sets field value
func (o *TaskConfigForm) SetENABLE_SEARCH_QUERY_GENERATION(v bool) {
	o.ENABLE_SEARCH_QUERY_GENERATION = v
}

// GetENABLE_RETRIEVAL_QUERY_GENERATION returns the ENABLE_RETRIEVAL_QUERY_GENERATION field value
func (o *TaskConfigForm) GetENABLE_RETRIEVAL_QUERY_GENERATION() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ENABLE_RETRIEVAL_QUERY_GENERATION
}

// GetENABLE_RETRIEVAL_QUERY_GENERATIONOk returns a tuple with the ENABLE_RETRIEVAL_QUERY_GENERATION field value
// and a boolean to check if the value has been set.
func (o *TaskConfigForm) GetENABLE_RETRIEVAL_QUERY_GENERATIONOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ENABLE_RETRIEVAL_QUERY_GENERATION, true
}

// SetENABLE_RETRIEVAL_QUERY_GENERATION sets field value
func (o *TaskConfigForm) SetENABLE_RETRIEVAL_QUERY_GENERATION(v bool) {
	o.ENABLE_RETRIEVAL_QUERY_GENERATION = v
}

// GetQUERY_GENERATION_PROMPT_TEMPLATE returns the QUERY_GENERATION_PROMPT_TEMPLATE field value
func (o *TaskConfigForm) GetQUERY_GENERATION_PROMPT_TEMPLATE() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.QUERY_GENERATION_PROMPT_TEMPLATE
}

// GetQUERY_GENERATION_PROMPT_TEMPLATEOk returns a tuple with the QUERY_GENERATION_PROMPT_TEMPLATE field value
// and a boolean to check if the value has been set.
func (o *TaskConfigForm) GetQUERY_GENERATION_PROMPT_TEMPLATEOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QUERY_GENERATION_PROMPT_TEMPLATE, true
}

// SetQUERY_GENERATION_PROMPT_TEMPLATE sets field value
func (o *TaskConfigForm) SetQUERY_GENERATION_PROMPT_TEMPLATE(v string) {
	o.QUERY_GENERATION_PROMPT_TEMPLATE = v
}

// GetTOOLS_FUNCTION_CALLING_PROMPT_TEMPLATE returns the TOOLS_FUNCTION_CALLING_PROMPT_TEMPLATE field value
func (o *TaskConfigForm) GetTOOLS_FUNCTION_CALLING_PROMPT_TEMPLATE() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TOOLS_FUNCTION_CALLING_PROMPT_TEMPLATE
}

// GetTOOLS_FUNCTION_CALLING_PROMPT_TEMPLATEOk returns a tuple with the TOOLS_FUNCTION_CALLING_PROMPT_TEMPLATE field value
// and a boolean to check if the value has been set.
func (o *TaskConfigForm) GetTOOLS_FUNCTION_CALLING_PROMPT_TEMPLATEOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TOOLS_FUNCTION_CALLING_PROMPT_TEMPLATE, true
}

// SetTOOLS_FUNCTION_CALLING_PROMPT_TEMPLATE sets field value
func (o *TaskConfigForm) SetTOOLS_FUNCTION_CALLING_PROMPT_TEMPLATE(v string) {
	o.TOOLS_FUNCTION_CALLING_PROMPT_TEMPLATE = v
}

func (o TaskConfigForm) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TaskConfigForm) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["TASK_MODEL"] = o.TASK_MODEL.Get()
	toSerialize["TASK_MODEL_EXTERNAL"] = o.TASK_MODEL_EXTERNAL.Get()
	toSerialize["ENABLE_TITLE_GENERATION"] = o.ENABLE_TITLE_GENERATION
	toSerialize["TITLE_GENERATION_PROMPT_TEMPLATE"] = o.TITLE_GENERATION_PROMPT_TEMPLATE
	toSerialize["IMAGE_PROMPT_GENERATION_PROMPT_TEMPLATE"] = o.IMAGE_PROMPT_GENERATION_PROMPT_TEMPLATE
	toSerialize["ENABLE_AUTOCOMPLETE_GENERATION"] = o.ENABLE_AUTOCOMPLETE_GENERATION
	toSerialize["AUTOCOMPLETE_GENERATION_INPUT_MAX_LENGTH"] = o.AUTOCOMPLETE_GENERATION_INPUT_MAX_LENGTH
	toSerialize["TAGS_GENERATION_PROMPT_TEMPLATE"] = o.TAGS_GENERATION_PROMPT_TEMPLATE
	toSerialize["ENABLE_TAGS_GENERATION"] = o.ENABLE_TAGS_GENERATION
	toSerialize["ENABLE_SEARCH_QUERY_GENERATION"] = o.ENABLE_SEARCH_QUERY_GENERATION
	toSerialize["ENABLE_RETRIEVAL_QUERY_GENERATION"] = o.ENABLE_RETRIEVAL_QUERY_GENERATION
	toSerialize["QUERY_GENERATION_PROMPT_TEMPLATE"] = o.QUERY_GENERATION_PROMPT_TEMPLATE
	toSerialize["TOOLS_FUNCTION_CALLING_PROMPT_TEMPLATE"] = o.TOOLS_FUNCTION_CALLING_PROMPT_TEMPLATE
	return toSerialize, nil
}

func (o *TaskConfigForm) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"TASK_MODEL",
		"TASK_MODEL_EXTERNAL",
		"ENABLE_TITLE_GENERATION",
		"TITLE_GENERATION_PROMPT_TEMPLATE",
		"IMAGE_PROMPT_GENERATION_PROMPT_TEMPLATE",
		"ENABLE_AUTOCOMPLETE_GENERATION",
		"AUTOCOMPLETE_GENERATION_INPUT_MAX_LENGTH",
		"TAGS_GENERATION_PROMPT_TEMPLATE",
		"ENABLE_TAGS_GENERATION",
		"ENABLE_SEARCH_QUERY_GENERATION",
		"ENABLE_RETRIEVAL_QUERY_GENERATION",
		"QUERY_GENERATION_PROMPT_TEMPLATE",
		"TOOLS_FUNCTION_CALLING_PROMPT_TEMPLATE",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTaskConfigForm := _TaskConfigForm{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTaskConfigForm)

	if err != nil {
		return err
	}

	*o = TaskConfigForm(varTaskConfigForm)

	return err
}

type NullableTaskConfigForm struct {
	value *TaskConfigForm
	isSet bool
}

func (v NullableTaskConfigForm) Get() *TaskConfigForm {
	return v.value
}

func (v *NullableTaskConfigForm) Set(val *TaskConfigForm) {
	v.value = val
	v.isSet = true
}

func (v NullableTaskConfigForm) IsSet() bool {
	return v.isSet
}

func (v *NullableTaskConfigForm) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTaskConfigForm(val *TaskConfigForm) *NullableTaskConfigForm {
	return &NullableTaskConfigForm{value: val, isSet: true}
}

func (v NullableTaskConfigForm) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTaskConfigForm) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


